#let setup_doc(title: "", author: "Anonymous", date: datetime.today().display(), body) = {

  let primary   = rgb("#0f172a")
  let accent    = rgb("#2563eb")
  let muted     = rgb("#64748b")
  let divider   = rgb("#e2e8f0")
  let surface   = rgb("#f8fafc")

  // Document Metadata 
  set document(author: author, title: title)

  // Page Layout
  set page(
    paper: "us-letter",
    margin: (top: 1.2in, bottom: 1.2in, left: 1.1in, right: 1.1in),
    header: context {
      if counter(page).get().first() > 1 [
        #set text(size: 8pt, fill: muted, weight: 500)
        #stack(dir: ltr, spacing: 1fr, upper(title), author)
        #v(-0.4em)
        #line(length: 100%, stroke: 0.5pt + divider)
      ]
    },
    footer: context {
      set text(size: 8pt, fill: muted)
      grid(
        columns: (1fr, 1fr),
        align(left)[Generated by #text(weight: 600)[doc-engine-cli]],
        align(right)[#counter(page).display() / #context counter(page).final().first()]
      )
    }
  )

  // Typography
  set text(font: ("Inter", "Helvetica Neue", "Arial"), size: 10pt, fill: primary, lang: "en")
  set par(justify: true, leading: 0.65em)

  // Code Blocks
  show raw.where(block: true): it => block(
    fill: rgb("#f6f8fa"),
    inset: (x: 14pt, y: 10pt),
    radius: 4pt,
    width: 100%,
    stroke: 0.5pt + divider,
    text(font: ("Cascadia Code", "Consolas", "Courier New"), size: 8.5pt, it)
  )

  show raw.where(block: false): it => box(
    fill: rgb("#f0f2f5"),
    inset: (x: 4pt, y: 2pt),
    radius: 2pt,
    text(font: ("Cascadia Code", "Consolas", "Courier New"), size: 9pt, it)
  )

  // Heading Styles
  show heading.where(level: 1): it => block(sticky: true, width: 100%)[
    #set text(size: 15pt, weight: 700, fill: primary)
    #v(1.5em)
    #it.body
    #v(0.3em)
    #line(length: 100%, stroke: 1.5pt + primary)
    #v(0.6em)
  ]

  show heading.where(level: 2): it => block(sticky: true)[
    #set text(size: 12.5pt, weight: 600, fill: accent)
    #v(1.2em)
    #it.body
    #v(0.4em)
  ]

  show heading.where(level: 3): it => block(sticky: true)[
    #set text(size: 11pt, weight: 600, fill: primary)
    #v(0.8em)
    #it.body
    #v(0.3em)
  ]

  // Cover Page
  align(left + horizon)[
    #v(-10%)
    #text(size: 36pt, weight: 800, tracking: -1.5pt, fill: primary)[#title]
    #v(2em)
    #block(stroke: (left: 3pt + accent), inset: (left: 1.2em))[
      #text(size: 11pt, weight: 600, fill: primary)[#author]
      #v(0.3em)
      #text(size: 10pt, fill: muted)[#date]
    ]
    #v(4em)
    #text(size: 9pt, fill: muted)[Generated with #text(weight: 600)[doc-engine-cli]]
    #pagebreak()
  ]

  // Table of Contents
  set align(left)
  show outline.entry.where(level: 1): it => {
    v(10pt, weak: true)
    strong(it)
  }

  outline(title: [Table of Contents], indent: 1.5em, depth: 3)
  pagebreak()

  // Body
  body
}
