#let setup_doc(title: "", author: "Anonymous", date: datetime.today().display(), bibliography_file: none, body) = {

  // Brand Colors (Cyber-Academic)
  let primary   = rgb("#0f172a")
  let accent    = rgb("#2563eb")
  let muted     = rgb("#64748b")
  let divider   = rgb("#e2e8f0")
  let surface   = rgb("#f8fafc")

  // Document Metadata 
  set document(author: author, title: title)

  // Page Layout (Scientific Format)
  set page(
    paper: "us-letter",
    margin: (top: 1.2in, bottom: 1.2in, left: 1.1in, right: 1.1in),
    header: context {
      if counter(page).get().first() > 1 [
        #set text(font: "Inter", size: 8pt, fill: muted, weight: 500)
        #stack(dir: ltr, spacing: 1fr, upper(title), author)
        #v(-0.4em)
        #line(length: 100%, stroke: 0.5pt + divider)
      ]
    },
    footer: context {
      set text(font: "Inter", size: 8pt, fill: muted)
      grid(
        columns: (1fr, 1fr),
        align(left)[Generated by #link("https://github.com/leonardosalasd/doc-engine-cli")[#text(weight: 600)[doc-engine-cli]]],
        align(right)[#counter(page).display() / #context counter(page).final().first()]
      )
    }
  )

  // Typography - Academic Body (Serif), Modern Headings (Sans-Serif)
  set text(font: ("Linux Libertine", "New Computer Modern", "Times New Roman"), size: 11pt, fill: primary, lang: "en")
  set par(justify: true, leading: 0.7em, first-line-indent: 1.2em)
  
  show heading: set text(font: ("Inter", "Helvetica Neue", "Arial"))

  // Code Blocks (Kept modern and sleek)
  show raw.where(block: true): it => block(
    fill: surface,
    inset: (x: 14pt, y: 10pt),
    radius: 4pt,
    width: 100%,
    stroke: 0.5pt + divider,
    text(font: ("Cascadia Code", "Consolas", "Courier New"), size: 8.5pt, fill: primary, it)
  )

  show raw.where(block: false): it => box(
    fill: surface,
    inset: (x: 4pt, y: 2pt),
    radius: 2pt,
    text(font: ("Cascadia Code", "Consolas", "Courier New"), size: 9pt, it)
  )

  // Heading Styles (Academic structured)
  show heading.where(level: 1): it => block(sticky: true, width: 100%)[
    #set text(size: 16pt, weight: 700, fill: primary)
    #v(1.5em)
    #it
    #v(0.3em)
    #line(length: 100%, stroke: 1.5pt + primary)
    #v(0.6em)
  ]

  show heading.where(level: 2): it => block(sticky: true)[
    #set text(size: 13pt, weight: 600, fill: accent)
    #v(1.2em)
    #it
    #v(0.4em)
  ]

  show heading.where(level: 3): it => block(sticky: true)[
    #set text(size: 11.5pt, weight: 600, fill: primary)
    #v(0.8em)
    #it
    #v(0.3em)
  ]

  // Cover Page (Tpxidian / Ilm inspired)
  align(left + horizon)[
    #v(-10%)
    #text(font: "Inter", size: 38pt, weight: 800, tracking: -1.5pt, fill: primary)[#title]
    #v(2.5em)
    #block(stroke: (left: 4pt + accent), inset: (left: 1.5em))[
      #text(font: "Inter", size: 12pt, weight: 600, fill: primary)[#author]
      #v(0.4em)
      #text(font: "Inter", size: 10.5pt, fill: muted)[#date]
    ]
    #v(5em)
    #text(font: "Inter", size: 9pt, fill: muted)[Compiled via #text(weight: 600, fill: accent)[doc-engine v0.1.2]]
    #pagebreak()
  ]

  // Table of Contents
  set align(left)
  show outline.entry.where(level: 1): it => {
    v(10pt, weak: true)
    strong(it)
  }

  show outline: it => block(width: 100%)[
    #set text(font: "Inter")
    #it
  ]

  outline(title: [Table of Contents], indent: 1.5em, depth: 3)
  pagebreak()

  // Body Content
  body

  // Bibliography Support
  if bibliography_file != none {
    pagebreak()
    set text(font: "Linux Libertine", size: 10pt)
    bibliography(bibliography_file, style: "ieee")
  }
}
